# Este arquivo de configuração é utilizado para definir os parâmetros necessários para a execução do sistema de controle autônomo no simulador Carla.
# Ele contém as seguintes seções:
#
# 1. Configuração do Carla:
#    - Define o host, porta e tempo limite para a conexão com o simulador Carla.
#
# 2. Configuração do Veículo:
#    - Especifica o tipo de veículo e o entre-eixos (wheelbase), que são importantes para o modelo de controle.
#
# 3. Configuração do MPC (Model Predictive Control):
#    - Define parâmetros para o controlador preditivo, como o passo de tempo (dt), horizonte de predição (horizon), e pesos para a função de custo (erros de trajetória, velocidade, etc.).
#    - Também inclui restrições de controle, como ângulo máximo de direção, aceleração máxima e frenagem máxima.
#
# 4. Frequência do Loop de Controle:
#    - Especifica a frequência com que o loop de controle será executado.

# Carla configuration
carla:
  host: localhost
  port: 2000
  timeout: 10.0

# Vehicle configuration
vehicle:
  type: vehicle.tesla.model3
  wheelbase: 2.7

# MPC configuration
mpc:
  dt: 0.1
  horizon: 10  # Increased from 3 to 15
  wheelbase: 2.7
  
  # Optimized cost function weights
  w_cte: 10.0        # Increased cross-track error weight
  w_etheta: 5.0      # Increased heading error weight  
  w_vel: 1.0         # Keep velocity weight moderate
  w_steer: 0.1       # Decreased to allow more steering freedom
  w_accel: 0.05      # Decreased to allow more acceleration
  w_steer_rate: 0.3  # Moderate steering rate constraint
  w_lane: 8.0        # Increased lane keeping weight
  
  # Less conservative control constraints
  max_steer: 0.52    # ~30 degrees (increased from 0.6)
  max_throttle: 0.8  # Increased from 1.0
  max_brake: 0.5     # Increased from 0.3
  max_iter: 500  # Increase solver iterations
  steering_limits: [-0.52, 0.52]  # ±30 degrees in radians
  throttle_limits: [0.0, 0.8]

# Control loop frequency
control_frequency: 0.1  # seconds

# Suggestion: Lower camera resolution for faster inference
# In your config/carla_config.yaml, set:
# camera_width: 320
# camera_height: 320
# This will reduce the image size and speed up the model and projection pipeline.
