# Este arquivo de configuração é utilizado para definir os parâmetros necessários para a execução do sistema de controle autônomo no simulador Carla.
# Ele contém as seguintes seções:
#
# 1. Configuração do Carla:
#    - Define o host, porta e tempo limite para a conexão com o simulador Carla.
#
# 2. Configuração do Veículo:
#    - Especifica o tipo de veículo e o entre-eixos (wheelbase), que são importantes para o modelo de controle.
#
# 3. Configuração do MPC (Model Predictive Control):
#    - Define parâmetros para o controlador preditivo, como o passo de tempo (dt), horizonte de predição (horizon), e pesos para a função de custo (erros de trajetória, velocidade, etc.).
#    - Também inclui restrições de controle, como ângulo máximo de direção, aceleração máxima e frenagem máxima.
#
# 4. Frequência do Loop de Controle:
#    - Especifica a frequência com que o loop de controle será executado.

# Carla configuration
carla:
  host: localhost
  port: 2000
  timeout: 10.0

# Vehicle configuration
vehicle:
  type: vehicle.tesla.model3
  wheelbase: 2.7

# MPC configuration
mpc:
  dt: 0.1  # Time step (seconds)
  horizon: 3  # Prediction horizon
  wheelbase: 2.7  # Vehicle wheelbase (meters)
  
  # Cost function weights
  w_cte: 3.5  # Cross-track error weight (aumentado para dar mais importância ao seguimento da trajetória)
  w_etheta: 2.0  # Heading error weight (aumentado para dar mais importância à orientação)
  w_vel: 1.0  # Velocity error weight
  w_steer: 0.2  # Steering input weight (decreased to allow more steering freedom)
  w_accel: 0.05  # Acceleration input weight (decreased to allow more acceleration)
  w_steer_rate: 0.5  # Steering rate weight (decreased to allow quicker steering changes)
  w_lane: 4.0     # Weight for staying in lane (increased to make it primary priority)
  
  # Control constraints
  max_steer: 0.6  # Maximum steering angle (radians) - increased to allow sharper turns
  max_throttle: 1.0  # Maximum throttle
  max_brake: 0.3  # Maximum brake (reduced to prevent excessive braking)

# Control loop frequency
control_frequency: 0.1  # seconds
