# Este arquivo de configuração é utilizado para definir os parâmetros necessários para a execução do sistema de controle autônomo no simulador Carla.
# Ele contém as seguintes seções:
#
# 1. Configuração do Carla:
#    - Define o host, porta e tempo limite para a conexão com o simulador Carla.
#
# 2. Configuração do Veículo:
#    - Especifica o tipo de veículo e o entre-eixos (wheelbase), que são importantes para o modelo de controle.
#
# 3. Configuração do MPC (Model Predictive Control):
#    - Define parâmetros para o controlador preditivo, como o passo de tempo (dt), horizonte de predição (horizon), e pesos para a função de custo (erros de trajetória, velocidade, etc.).
#    - Também inclui restrições de controle, como ângulo máximo de direção, aceleração máxima e frenagem máxima.
#
# 4. Frequência do Loop de Controle:
#    - Especifica a frequência com que o loop de controle será executado.

# Carla configuration
carla:
  host: localhost
  port: 2000
  timeout: 10.0

# Vehicle configuration
vehicle:
  type: vehicle.tesla.model3
  wheelbase: 2.7

# MPC configuration
mpc:
  dt: 0.1  # Time step (seconds)
  horizon: 10  # Prediction horizon
  wheelbase: 2.7  # Vehicle wheelbase (meters)
  
  # Cost function weights
  w_cte: 1.0  # Cross-track error weight
  w_etheta: 1.0  # Heading error weight
  w_vel: 0.5  # Velocity error weight
  w_steer: 0.5  # Steering input weight
  w_accel: 0.1  # Acceleration input weight
  w_steer_rate: 1.0  # Steering rate weight
  
  # Control constraints
  max_steer: 0.5  # Maximum steering angle (radians)
  max_throttle: 1.0  # Maximum throttle
  max_brake: 1.0  # Maximum brake

# Control loop frequency
control_frequency: 0.1  # seconds
